### ISSUE TITLE
Cap `lsp.progress` messages

### ISSUE THREAD

**Issue by ofirgall** [folke/noice.nvim#166]
[ltex-ls](https://github.com/valentjn/ltex-ls) sending `checking document` while I type, I know its the server fault but I would like to cap the amount of `lsp.progress` messages `noice` renders at a current moment, if I could configure it to a specific server it would be even noicer.

![image](https://user-images.githubusercontent.com/4954051/198823955-c43a681f-86cb-42f5-83da-4be17629d129.png)

**Comment by ranjithshegde** [comment]
I am working on a wiki that will be updated later today with guides for using notify-tokens to customize/avoid some of these messages. 

That should address this specific issue as well.

**Comment by folke** [comment]
@ranjithshegde thanks!

I can also make an option to not use the lsp progress token.

**Comment by folke** [comment]
The best fix is simply doing:
```lua
  vim.diagnostic.config({
     update_in_insert = false
  })
```

**Comment by ofirgall** [comment]
Thanks for the quick reply.
btw one of the greatest nvim plugins, I can't imaging going back to use a vanilla cmdline

**Comment by folke** [comment]
Thanks!

**Comment by life00** [comment]
I am sorry but I really don't understand what I am doing wrong. I am using LazyVim and ltex-ls. In theory it shouldn't even result in this behavior because `update_in_insert = false` is set by default. For the purpose of reproducibility I installed a clean LazyVim version with only modifications including the file on the left and ltex-ls installed.

https://github.com/folke/noice.nvim/assets/108618401/f0dc0e79-b412-4be0-bdb9-21f84223eac2

Of course it is possible to disable progress, or throttle it. But this is not an ideal solution because I like this UI element, and I would like to keep it on and responsive. Any suggestions?

**Comment by life00** [comment]
It appears that `update_in_insert = false` works as expected, but it does not affect noice.nvim behavior. When its false LSP diagnostic updates are not accepted  while in insert mode (you may see this in the video above), however this does not seem to apply to noice.nvim. Of course the actual problem is with the LSP itself, but maybe there is a workaround? If not then I think I will either do this: https://github.com/folke/noice.nvim/issues/537#issuecomment-1637528605 or try to disable progress per filetype or LSP.

**Comment by life00** [comment]
for those who are searching for a solution: https://github.com/LazyVim/LazyVim/discussions/1182#discussioncomment-6624575
