### ISSUE TITLE
Fix scroll

### ISSUE THREAD

**Issue by folke** [folke/noice.nvim#210]
While I no longer see the error now, I also do not get the scrolling motion in the hover. Is it working for you? Or perhaps I misunderstood: this is for the hover `K`, namely hover on function and scroll (not for the completion menu window, whose scrolling is working fine), is it not?

_Originally posted by @gennaro-tedesco in https://github.com/folke/noice.nvim/issues/161#issuecomment-1310194757_

**Comment by folke** [comment]
@gennaro-tedesco scroll should work as expect. It's indeed for `K`.

**Comment by folke** [comment]
Have you added the keymaps?

```lua
  vim.keymap.set("n", "<c-f>", function()
    if not require("noice.lsp").scroll(4) then
      return "<c-f>"
    end
  end, { silent = true, expr = true })

  vim.keymap.set("n", "<c-b>", function()
    if not require("noice.lsp").scroll(-4) then
      return "<c-b>"
    end
  end, { silent = true, expr = true })
```

**Comment by gennaro-tedesco** [comment]
Yes, I have added the keymaps but it still does nothing. The `if` condition evaluates to true, however the invocation of `require("noice.lsp").scroll(-4)` does nothing: I have also tried to explicitly call the function rather than executing the keymap (with the idea that for whichever reason the keymap would not have been registered) but I still get no behaviour (no errors, but also nothing happening).

However, if you are saying that it does work, I will continue looking into it myself (no need for you to spend more time on it)!

**Comment by folke** [comment]
Have you tried both directions? Superweird.

**Comment by gennaro-tedesco** [comment]
I am having a look at [this line](https://github.com/folke/noice.nvim/blob/e5092c284a6ffd44e8d09f5efbe29395190c77f9/lua/noice/lsp/docs.lua#L50): does the condition `if win` imply that I have to be (with my cursor) _into_ the hover window for the scrolling to take effect? Because if I move my cursor into the hover window (`K` and then `K` again) then it does work. But I was expecting a behaviour similar to the hotkeys of `nvim-cmp` where I could scroll the window with the cursor still where it was (namely even in insert mode) without having to focus onto the completion window menu.

If that is the case, sorry for my misunderstanding!

**Comment by folke** [comment]
no, no, it should indeed work the same as with cmp.
You could check the return of the scroll function. It should be `true` if a window has been scrolled.

**Comment by folke** [comment]
The `win`, is the window where the message is displayed. You can show `hover` and `signature` in any Noice view, but will be shown in a hover popup by default.

**Comment by folke** [comment]
Now that I think about it, maybe the mapping is conflicting with the `cmp` docs mapping?
Try disabling the cmp mapping, or use another temporary mappping for Noice to test it.

**Comment by folke** [comment]
Or check with `:map <c-f>`

**Comment by folke** [comment]
Nevermind, since it also doesnt work if you call `scroll` directly

**Comment by gennaro-tedesco** [comment]
I have managed to have it work by explicitly invoking the call in an `else` condition, namely:
```lua
vim.keymap.set("n", "<c-f>", function()
    if not require("noice.lsp").scroll(4) then
      return "<c-f>"
    else
     require("noice.lsp").scroll(4)
    end
  end, { silent = true, expr = true })
```
Just for the sake of curiosity, is an idiomatic expression like
```lua
if not require("noice.lsp").scroll(4) then
  return "<c-f>"
end
```
supposed to work? Namely the condition `require("noice.lsp").scroll(4)` is both evaluated and executed? Because it seems that what prevented it to work was the fact that no explicit call of said expression was present as `else` (positive case when we are indeed in an hover window).

All is well that ends well! :D

**Comment by folke** [comment]
That doesnt make any sense :)
You're now just calling the scroll function twice.

Your code is the same as:
```lua
vim.keymap.set("n", "<c-f>", function()
   require("noice.lsp").scroll(4)
  if not require("noice.lsp").scroll(4) then
    return "<c-f>"
  end
end, { silent = true, expr = true })
```
Really weird you have to call it twice.

Must be something to do with your scroll settings. Do you set any special scrolling options? Like `scrolloff` etc? Did you make any customizations to the `hover` view?

**Comment by gennaro-tedesco** [comment]
>  Like scrolloff etc?

I do have `scrolloff` set, for that matter; do you think it may affect this behaviour? The `hover` view doesn't have any special customisation.

However, later in the day I will try to start from the ground up and re-construct all of this starting from a clean vim. I agree there must be somewhere in my settings/mappings that causes the first invocation to not take effect.

**Comment by folke** [comment]
Do you have `splitkeep` set in your config? I fixed an issue with that, that might've fixed this problem you have.

**Comment by gennaro-tedesco** [comment]
The option is set by default to
```vim
set splitkeep?
cursor
```
and I did not change it: would it in any way impact the scrolling?

(I believe we can however close this issue: while it may be useful for others as reference, you've already put too much work in it!!)

**Comment by folke** [comment]
ok, I will :)

Good that you have a work around

**Comment by dlvhdr** [comment]
Just FYI, I also had this issue and it was simply because I didn't set the keymap to also work in `insert` mode.
