### ISSUE TITLE
cmdwin doesn't work correctly

### ISSUE THREAD

**Issue by p00f** [folke/noice.nvim#66]
**Describe the bug**
cmdwin doesn't work correctly - `q:` then `/`/`?` to search doesn't show what I'm typing (neither in floating window nor in the normal place). `q?`/`q/` just moves my cursor to the cmdwin instead of searching

**Which version of Neovim are you using?**
https://github.com/neovim/neovim/commit/1c478391ca7754bf5ecb4b76c29acfa9b4978393

**To Reproduce**
1. Press `q?` in normal mode - cmdwin gets focused instead of searching - pressing `a` here will start insert mode, for example.
2. Press `q:` then `/` or `?` - search is started but input is not shown anywhere

**Expected Behavior**
Floating popup shows my input

**Screenshots**

https://user-images.githubusercontent.com/36493671/195987637-5855cf79-7782-4986-81c0-668acae0031c.mp4

*Noice Log**
Please include any related errors from the Noice log file. (open with `:Noice log`)

<details>
<summary>Noice log</summary>
<pre>
paste log here
</pre>
</details>

**Comment by folke** [comment]
Opening the cmdline from the cmdline-window, opens a new cmdline at a new level (Neovim internals)

I had already added support for multi-level cmdlines, but it didn't work in cases where the first level cmdline was closed.

I think I just fixed all of this, but there might be additional issues left due to the cmdline-window being a very special window in Neovim. (see `:h E11`). So do let me know if you still see things that don't look right.

**Comment by p00f** [comment]
The second issue (`q:` then `/`) is fixed 🎉  but the first one (`q?`) is still there

**Comment by folke** [comment]
1. is how Neovim works? I don;t see what's wrong there.

If you disable Noice and do those steps you get the same result? What do you think should be different?

**Comment by folke** [comment]
Closing this, since the remaining issue is standard Neovim behavior. Let me know if this is incorrect

**Comment by levouh** [comment]
I've just started using [cmdbuf.nvim](https://github.com/notomo/cmdbuf.nvim) and have never looked back. Deals with all the fun issues that come along with the "special" nature of the command-line window.
