### ISSUE TITLE
bug: in search input, when text is deleted, it is still visible

### ISSUE THREAD

**Issue by Galicarnax** [folke/noice.nvim#892]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Arch Linux

### Describe the bug

While searching, press `<backspace>` until cursor gets to the beginning of the line. The first character stays visible. Type new symbols, that character is gone. Or press `<c-w>` to delete preceding words, until cursor is at the beginning of the line. The entire first word stays visible. Type something new, that word is gone. This behavior is not observed in command mode (`:`), only in search mode (`/` or `?`). It happens both with `view = "cmdline"` and `view = "cmdline_popup"`. This behavior emerged recently (1-2 weeks perhaps) after one of the updates. Could reproduce with minimal `repro.lua`.

### Steps To Reproduce

1. Do search: `/some text`.
2. Press `<c-w>` twice to delete both words.
3. The word `some` is still there (but is gone when you type something new)

### Expected Behavior

Input should be completely cleared when text is deleted.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/noice.nvim", opts = {} },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Kaiser-Yang** [comment]
I meet the same issue.

**Comment by SuXYIO** [comment]
Same issue.

**Comment by dpetka2001** [comment]
To add to this, I also noticed that when you have `mini.pairs` enabled with option `modes = { command = true }` it also doesn't show the pair of parenthesis in search mode for example (most of the times, because a few times it does show it). 

I tried different commits to see where this behavior started happening and found out that the last working commit is `b3f08e6`. After that commit it stopped working. The culprit seems to be something in [real cursors commit](https://github.com/folke/noice.nvim/commit/5b5fa91).

**Comment by dpetka2001** [comment]
So, I tried testing something. I created an autocmd
```lua
vim.api.nvim_create_autocmd("CmdlineChanged", {
  group = vim.api.nvim_create_augroup("update_search_redraw", {}),
  desc = "Update search redraw",
  callback = function()
    vim.schedule(function()
      vim.cmd("redraw")
    end)
  end,
})
```
Not sure how safe this is, since it mentions
> Be careful not to mess up the command line, it may cause Vim to lock up.

Still in testing phase, I haven't observed any lock ups. But if you encounter any problems, it might be because of this autocmd, so use it at your own risk. This is not a suggestion to solve the problem at hand, it's just something I'm experimenting with.

Hopefully Folke will have some more insight after he comes back.

**Comment by hb0nes** [comment]
> So, I tried testing something. I created an autocmd
> 
> ```lua
> vim.api.nvim_create_autocmd("CmdlineChanged", {
>   group = vim.api.nvim_create_augroup("update_search_redraw", {}),
>   desc = "Update search redraw",
>   callback = function()
>     vim.schedule(function()
>       vim.cmd("redraw")
>     end)
>   end,
> })
> ```
> 
> Not sure how safe this is, since it mentions
> 
> > Be careful not to mess up the command line, it may cause Vim to lock up.
> 
> Still in testing phase, I haven't observed any lock ups. But if you encounter any problems, it might be because of this autocmd, so use it at your own risk. This is not a suggestion to solve the problem at hand, it's just something I'm experimenting with.
> 
> Hopefully Folke will have some more insight after he comes back.

Wow how did you find this out?
I was having a completely different issue, where text wasn't showing up for me AT ALL while searching with noice, unless `cmp` was showing me completions.

The only conclusion I can draw with my limited knowledge is that noice is not redrawing properly.

With your change (snappy/fast):
![image](https://github.com/user-attachments/assets/04a34c57-c2c4-4572-aa23-692b039ff054)

Without:
![image](https://github.com/user-attachments/assets/79a9d085-61d0-4aa5-9355-871daaf744a7)

**Comment by dpetka2001** [comment]
`noice` does not seem to be redrawing while in search mode (or at least not redrawing properly). It was just a lucky guess while searching through the commits and found [this one](https://github.com/folke/noice.nvim/commit/b3f08e6cf0fd30847f299cc94707563920fd2139). Of course the code has changed since then and now the relevant code is [here](https://github.com/folke/noice.nvim/blob/448bb9c524a7601035449210838e374a30153172/lua/noice/util/hacks.lua#L30-L50) and [here](https://github.com/folke/noice.nvim/blob/448bb9c524a7601035449210838e374a30153172/lua/noice/ui/cmdline.lua#L231-L246), but still I'm not familiar with `noice`'s codebase, so this is all just a deduction from my part (which might be entirely wrong, since I don't understand that much to be honest). 

Then I just tried to experiment with triggering a redraw in `cmdline` mode and was going through the events in Neovim autocmds to see what I could use. I also tried to add `flush = true` in [this line](https://github.com/folke/noice.nvim/blob/448bb9c524a7601035449210838e374a30153172/lua/noice/ui/cmdline.lua#L245), but there was a visual flickering effect and did not like it. 

I'm sure Folke is much more knowledgeable and will have a better response than mine. This is just something I'm experimenting with after all just based on pure hunch. It doesn't seem to cause any problems, but I can't be 100% sure due to my lack of knowledge and understanding.

**Comment by gengdz** [comment]
Same issue.

**Comment by steve21168** [comment]
> > So, I tried testing something. I created an autocmd
> > ```lua
> > vim.api.nvim_create_autocmd("CmdlineChanged", {
> >   group = vim.api.nvim_create_augroup("update_search_redraw", {}),
> >   desc = "Update search redraw",
> >   callback = function()
> >     vim.schedule(function()
> >       vim.cmd("redraw")
> >     end)
> >   end,
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure how safe this is, since it mentions
> > > Be careful not to mess up the command line, it may cause Vim to lock up.
> > 
> > 
> > Still in testing phase, I haven't observed any lock ups. But if you encounter any problems, it might be because of this autocmd, so use it at your own risk. This is not a suggestion to solve the problem at hand, it's just something I'm experimenting with.
> > Hopefully Folke will have some more insight after he comes back.
> 
> Wow how did you find this out? I was having a completely different issue, where text wasn't showing up for me AT ALL while searching with noice, unless `cmp` was showing me completions.
> 
> The only conclusion I can draw with my limited knowledge is that noice is not redrawing properly.
> 
> With your change (snappy/fast): ![image](https://private-user-images.githubusercontent.com/38855893/354182459-04a34c57-c2c4-4572-aa23-692b039ff054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzAzOTYsIm5iZiI6MTcyNjE3MDA5NiwicGF0aCI6Ii8zODg1NTg5My8zNTQxODI0NTktMDRhMzRjNTctYzJjNC00NTcyLWFhMjMtNjkyYjAzOWZmMDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE5NDEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljM2ZhMmE2OTljZDlmNGZjMjMwYWFkZWQ0ZDljYmJkOTZlOGY0ZWVlMjNhNGE1ZjdmYjIwNDMyMjQzMmU0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ObwjFZWVQhmeTcYZxqwdLrYlcKXlcJyNtVd3UvM94HU)
> 
> Without: ![image](https://private-user-images.githubusercontent.com/38855893/354182698-79a9d085-61d0-4aa5-9355-871daaf744a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzAzOTYsIm5iZiI6MTcyNjE3MDA5NiwicGF0aCI6Ii8zODg1NTg5My8zNTQxODI2OTgtNzlhOWQwODUtNjFkMC00YWE1LTkzNTUtODcxZGFhZjc0NGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE5NDEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYWE1ZmM3YzhjYWJhMDM2NzU1ZDVkNzU0NmI1NTUxZmY1MjE3OTQ0M2M2YzdiYTZlMDcyZjE2NzVmOWZlNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dCQiE3D5OPWRmcBMWuePP56UPJc_OUKvNgKmLOV6Ev4)

I have this same issue where the search text wasn't showing at all. The redraw auto command is also a successful workaround for me.

**Comment by dpetka2001** [comment]
Please do bare in mind that my knowledge is very limited and this was purely based on me testing things out. In case you have other side effects, this autocmd might be at fault (it already has a warning about this on the help page of the `CmdLineChanged` event that I've already mentioned in my previous post). Again, the more correct way will surely be something that Folke comes up with to solve this problem. I'm just not at that level to understand and come up with a proper solution with regards to `noice`'s codebase.

**Comment by hb0nes** [comment]
Not stale.
