### ISSUE TITLE
bug: Weird Scrollbar Appears on UI

### ISSUE THREAD

**Issue by leehpham** [folke/noice.nvim#949]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

MacOS 14.6.1

### Describe the bug

![Screenshot 2024-09-15 at 9 29 09 AM](https://github.com/user-attachments/assets/cfa97ca2-437a-44c8-b505-0abe77b162e8)

This weird scrollbar keeps randomly appearing on the UI.
Once it shows up, it doesn't go away.
When I quit NeoVim and reopen, it goes away but it appears again shortly.

This seems like it has something to do with the dialog box of the API doc (Shift + K shows these dialog boxes).

I'm using LazyVim by the way.

### Steps To Reproduce

1. Open a TypeScript file with Neovim.
2. Start writing some code.
3. View the API doc of a certain API by placing the cursor over it and press Shift + K.

### Expected Behavior

The weird scrollbar shouldn't appear on the UI.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/noice.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by abusch** [comment]
Can confirm! Same `neovim` version and OS as the OP. I haven't been able to figure out what triggers it to appear...

**Comment by maxkemzi** [comment]
I experience the same bug.

**Neovim version:** 0.10.1
**Operating system:** Debian 12

**Comment by OnlyWick** [comment]
Same issue.

**Comment by hjalmarlucius** [comment]
Same issue.

**Comment by Raphael-Soares** [comment]
Same issue.

**Comment by ImmanuelKannan** [comment]
Same issue.

**Comment by folke** [comment]
I can't reproduce this and never saw this before.
Please provide a step by step repro so I can look into this.

**Comment by Fricker95** [comment]
I had the same issue but doing this removed the scrollbar so it doesn't show up anymore therefore doesn't stick around after the hover view disappears:
`views = {
        hover = {
          scrollbar = false,
        }
      },`

**Comment by MikeBellika** [comment]
> I can't reproduce this and never saw this before. Please provide a step by step repro so I can look into this.

@folke Managed to get a reproduction. I think it happens in insert mode, if the API doc overflows the pane and is then dismissed by typing. Bit hard to explain with text but I got it on video:

https://github.com/user-attachments/assets/fcc78bf8-1424-42b6-ba37-ecd15e5f8f4f

Three things to see in the video:
1. When the screen is too small vertically, the scrollbar stays (Happens at around 7 seconds)
2. When it has enough space, no scrollbar disappears correctly (Around 30 seconds)
3. When it doesn't have enough horizontal space, due to the split it happens again (34 seconds)

Please let me know if this doesn't make sense. The repo I used is here: https://github.com/MikeBellika/noice-scroll-repro

PS. Thank you for LazyVim, it's the best editor I've used so far!

**Comment by Joe-273** [comment]
When using the :Noice history command, if the content height is too high and a scrollbar appears, the scrollbar does not disappear when the window is closed.

![image](https://github.com/user-attachments/assets/3e923238-a2a7-4254-8f0f-1017e880b8bd)
![image](https://github.com/user-attachments/assets/9daee37a-beda-459d-8a98-b0634fc7a623)
