### ISSUE TITLE
bug: CmdLine % autocomplete leaves % at the start of the file path

### ISSUE THREAD

**Issue by mxaddict** [folke/noice.nvim#994]
### Did you check docs and existing issues?

- [X] I have read all the noice.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of noice.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Arch

### Describe the bug

When running a command like vsp in CmdLine then typing %->tab to autocomplete current filepath the autocomplete works, but % remains at the start of the string

![image](https://github.com/user-attachments/assets/f9412769-4d7b-4191-b0f4-d769430aea70)

![image](https://github.com/user-attachments/assets/d974b4f3-0d65-48ee-b27c-2e5a3304a6d8)

### Steps To Reproduce

1. Open vim
1. type `:tabnew %<tab>`

### Expected Behavior

Should complete the % variable as the current buffer path and replace the % symbol with the value

**Comment by dpetka2001** [comment]
It seems you're using [cmp-cmdline](https://github.com/hrsh7th/cmp-cmdline). So, that handles the completion for the command line. Because this doesn't happen with native Neovim completion when using `noice.nvim`. 

So, perhaps you should create an issue at that repo to solve this. I also tested on a minimal repro without `noice.nvim` and the same thing happens when `cmp-cmdline` is present.

**Comment by mxaddict** [comment]
Thanks!
